---
- name: Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/admin-user
    - name: Copy WAR file
      copy:
       src: target
       dest: /home/admin-user
    - name : Build image
      command: docker build -t ramarao388/zomato .
    - name : Push Docker Image
      command: docker push ramarao388/zomato
- name: Deployment into Kubernetes Cluster
  hosts: eks
  tasks:
   - name: 
     copy:
       src: DeploymentIntoK8sCluster.yml
       dest: /home/admin-user
   - name: 
     copy:
       src: LB-Service.yml
       dest: /home/admin-user
   - name : K8S Deployment
     command: kubectl apply -f DeploymentIntoK8sCluster.yml
   - name : LB Service
     command: kubectl apply -f LB-Service.yml
